### ISSUE TITLE
为什么不直接翻译qt目录下的html文件

### ISSUE THREAD

**Issue by peng-1998** [QtDocumentCN/QtDocumentCN#63]
我挺喜欢Qt的，也一直希望可以有中文文档，但是我想问为什么不直接翻译Qt目录下的html文件，这样其他人可以通过替换文件的方式把QtCreater的内置文档变成中文的。我挺想跟你们一起干的，但是我现在还在复习准备考研，时间不多，而且说实话那些地址转换，markdown编辑之类的令我望而却步，markdown我也只会一点。

**Comment by ZgblKylin** [comment]
翻译 html 工作量远高于 markdown，如果你读了它俩的源码就懂了。

另外，Qt 官方文档也不是手写 html 的，而是直接通过 doxygen，从注释导出到 html。

然而翻译分散在数万个文件里的几百万处注释工作量更大，因此翻译 markdown 已经是工作量最小的方式。

最后，如果你希望长期做编程这门行当，那么 markdown 是必修课，不然你会连 `README.md` 都玩不转。
