### ISSUE TITLE
许可证中的 ND（禁止演绎）限制了他人使用 Pull Requests 进行协作

### ISSUE THREAD

**Issue by ouuan** [QtDocumentCN/QtDocumentCN#65]
[CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh) 禁止他人分发修改后的作品。因此，如果我在 GitHub 上 fork 本项目并进行修改，就违反了许可证。建议将许可证修改为 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 或 [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.zh)。

> Once you start modifying that fork, then you're violating the license.
>
> [open source - Does using Creative Commons No-Derivatives license conflict with GitHub terms? - Software Engineering Stack Exchange](https://softwareengineering.stackexchange.com/questions/205167/does-using-creative-commons-no-derivatives-license-conflict-with-github-terms) 的评论

**Comment by ZgblKylin** [comment]
多谢科普，没想到fork也算nd……改到sa了
