### ISSUE TITLE
Reserved by leytou until 2020-07-31？这是怎么了？？？

### ISSUE THREAD

**Issue by CaiJi-bai** [QtDocumentCN/QtDocumentCN#70]
**需求文档**

请贴出需要翻译的文档链接（基于 [doc.qt.io](doc.qt.io)）。

若有一组文档，请贴出链接列表，或用相对精准的语句描述涵盖的文档范围，如多线程并发部分的类文档。

**需求原因**

请给出为何需要社区优先翻译的原因，包括但不限于：
- 有助于社区发展，即对大部分 Qt 开发者和读者更有需求，更适合优先翻译；
- 教学需要，此处指高校等正式类型教学或培训，不包括公众号卖课等商业用途；
- 个人学习需要；
- 个人开发参考需要；
- 商务需要，包括培训机构、自媒体培训、自媒体文章合作、企业需求等。

本社区会优先考虑社区发展需求，其次为教学需求，然后是个人需求和商务需求。

个人需求建议参与社区翻译，能力不足的话可以与社区成员共同合作翻译。

教育需求建议与社区微信群或负责人邮件进行深入联系，社区会协助教师的教学需求进行缺失的文档翻译，以及进一步的教学合作。

商务需求请先考虑赞助社区，或者通过参与翻译、丰富工具链、丰富发布渠道等形式反馈社区。

**Comment by ZgblKylin** [comment]
麻烦贴一下标题中说的是哪篇文档。

reserved 文档主要是社区成员为计划翻译一组互相关联的文档时提前占位，避免不同人翻译风格不一致或进度不一致造成后期关联内容调整的额外工作量。

如果标注reserve的该名人员目前并不活跃，或reserve标注已超时，那么该文档依然可以开放编辑。

若有意向参与该篇文档翻译，可以直接提交pr。
